/**
 * Root route that wires global layout, theming, and page rendering.
 *
 * Think of the root route as the app's outer frame:
 * - It defines the document HTML wrapper (`<html>`, `<head>`, `<body>`).
 * - It provides global providers (the Radix Theme in this case).
 * - It renders shared UI that should appear on every page (header/footer).
 * - It reserves a slot where nested route content will be rendered (`<Outlet />`).
 *
 * Rendering model in this app - SSG for static shell and SSR for dynamic content.
 * SSR is disabled at all in react-router.config.ts.
 * - The static shell (header/footer/main structure) is prerendered and built into static html files.
 * - `<Outlet />` is a placeholder where nested route modules render inside the shell.
 * - Route-specific data can be fetched by each route's loader/clientLoader.
 * - loaders are executed during build and will be included as static html content.
 * - clientLoader will be bundled as javascript code and executed in the browser.
 */
import "@radix-ui/themes/styles.css";
import "~/styles/app.css";
import "~/styles/themes.css";

import { Box, Container, Flex, Section, Theme } from "@radix-ui/themes";
import { type ReactNode } from "react";
import { Links, Meta, Outlet, Scripts, ScrollRestoration } from "react-router";

import { Footer } from "~/components/footer";
import { Header } from "~/components/header";
import { HTML_LANG } from "~/config";
import { useTheme } from "~/hooks/use-theme";

/**
 * `Layout` defines the full HTML document structure.
 *
 * In React Router framework mode, this component wraps your route tree and is
 * responsible for document-level elements.
 *
 * `children` is the already-rendered route app content passed in by the router.
 * Think of it as a placeholder where the currently matched child route component renders.
 */
export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang={HTML_LANG}>
      <head>
        <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        {/* Injects route `meta` exports (title, description, etc.). */}
        <Meta />
        {/* Injects route `links` exports as `<link>` tags. */}
        <Links />
      </head>
      <body>
        {/* Application UI generated by the route tree is rendered here. */}
        {children}
        {/* Restores scroll position on back/forward navigation automatically. */}
        <ScrollRestoration />
        {/* Injects React Router/client runtime scripts at the end of body. */}
        <Scripts />
      </body>
    </html>
  );
};

/**
 * `App` is the visual root of your route tree.
 *
 * This is where we configure theming and global page layout that should remain
 * consistent while the user navigates between nested routes.
 */
const App = () => {
  // Custom hook that stores theme state and exposes a toggle handler.
  // `appearance` is typically "light" or "dark".
  const { appearance, toggleTheme } = useTheme();

  return (
    // Radix UI theme provider: all Radix components and custom components with
    // neccesary css vars inside inherit these design tokens.
    /*
      Theme props:
      - appearance: selects light/dark token set.
      - radius: sets default component corner roundness.
      - scaling: scales spacing/typography/sizing globally.
    */
    <Theme appearance={appearance} radius="medium" scaling="100%">
      {/*
        Outer shell element for app-wide styling.
        - `minHeight="100vh"` ensures full viewport height.
        - `data-theme` can be used by custom CSS selectors for light/dark behavior.
      */}
      <Box className="app-shell" data-theme={appearance} minHeight="100vh">
        {/* Shared top navigation/header visible on every route. */}
        <Header appearance={appearance} onToggleTheme={toggleTheme} />
        {/* Vertical layout: main content grows, footer stays at bottom. */}
        <Flex direction="column" minHeight="100vh">
          {/* `asChild` makes Box pass its props/styles onto the `<main>` element directly. */}
          <Box asChild flexGrow="1" pt="9">
            <main>
              {/* Page content spacing wrapper. */}
              <Section py="6">
                {/* Constrains content width and adds horizontal padding. */}
                <Container px="4" size="4">
                  {/*
                    Most important React Router concept here:
                    `<Outlet />` is a placeholder where the currently matched
                    child route component renders.

                    Example:
                    - URL `/` may render `routes/home.tsx` here.
                    - URL `/about` may render `routes/about.tsx` here.
                    The root shell remains mounted, only outlet content changes.
                  */}
                  <Outlet />
                </Container>
              </Section>
            </main>
          </Box>
          {/* Shared footer visible on every route. */}
          <Footer />
        </Flex>
      </Box>
    </Theme>
  );
};
export default App;
