"""

Revision ID: 80cf0b013b8c
Revises: 
Create Date: 2026-10-04 10:44:57.604935

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80cf0b013b8c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("posts",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="Primary key."),
    sa.Column("title", sa.String(length=255), nullable=False, comment="Human-readable headline shown in lists and detail views."),
    sa.Column("content", sa.Text(), nullable=False, comment="Body in HTML format (e.g. <p>Hello</p>)."),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False, comment="When the post was created (UTC / TIMESTAMPTZ)."),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False, comment="When the post was last updated (UTC / TIMESTAMPTZ)."),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
