name: GitHub CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          make install-backend-dev
          make install-frontend

      - name: Run linters
        run: |
          make lint-backend
          make lint-frontend

      - name: Run tests
        run: |
          make test-backend
